using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Data;
using System.Configuration;
namespace SwankInnovation
{
    public partial class AddClient : System.Web.UI.Page
    {
        SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["Swank"].ConnectionString);
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                autogenerated();
                GridView1.DataBind();
            }
        }
        protected void Button1_Click(object sender, EventArgs e)
        {
            SqlCommand cmd = new SqlCommand("insert into ClientPoject(ClientID,CompanyName,ContactNo,Technology,Email,ProjectDuration,DeadLine) values('" + txt1.Text + "','" + txt5.Text + "','" + txt2.Text + "','" + DropDownList1.SelectedItem.Text + "','" + txt3.Text + "','" + txt6.Text + "','" + txt4.Text.Replace("'", "''") + "')", conn);
            conn.Open();
            cmd.ExecuteNonQuery();
            conn.Close();
            autogenerated();
            txt2.Text = "";
            txt3.Text = "";
            txt4.Text = "";
            txt5.Text = "";
            txt6.Text = "";
            DropDownList1.SelectedValue = "-1";
            GridView1.DataBind();
        }
        private void autogenerated()
        {
            string code = "SIPL";
            conn.Open();
            SqlCommand cmd = new SqlCommand("Select max(id) from ClientPoject", conn);
            int i = Convert.ToInt32(cmd.ExecuteScalar());
            conn.Close();
            i++;
            txt1.Text = code + i.ToString();
        }
    }
}