using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Data;
using System.Configuration;
using System.IO;
namespace SwankInnovation
{
    public partial class AddEmployee : System.Web.UI.Page
    {
        SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["Swank"].ConnectionString);
        SqlCommand cmd;
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                autogenerated();
                GridView1.DataBind();
            }
        }
        protected void btnSubmit_Click(object sender, EventArgs e)
        {
            string folderPath = Server.MapPath("~/Swank/");
            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }
            try
            {
                if (fileupload1.HasFile)
                {
                    fileupload1.SaveAs(folderPath + Path.GetFileName(fileupload1.FileName));
                    //Image1.ImageUrl = "~/Swank/" + Path.GetFileName(fileupload.FileName);
                    cmd = new SqlCommand("insert into AddEmployee(EmployeeId,EmployeeName,Email,Mobile,Qualification,Aaddress,Gender,Photo,Designation,city,BasicSalary,EmergencyNo,AlternateNo) values('" + txt1.Text + "','" + txt2.Text + "','" + txt3.Text + "','" + txt4.Text + "','" + txtqulfction.Text + "','" + txtaddress.Text.Replace("'", "''") + "','" + radio1.SelectedValue.ToString() + "','" + "~/Swank/" + fileupload1.FileName + "','" + txtdsgntion.Text + "','" + txtcity.Text + "','" + TextBox1.Text + "','"+TextBox2.Text+"','"+TextBox3.Text+"')", conn);
                    conn.Open();
                    SqlDataReader dr = cmd.ExecuteReader();
                    conn.Close();
                    txtdsgntion.Text = "";
                    txtcity.Text = "";
                    txt2.Text = "";
                    txt3.Text = "";
                    txt4.Text = "";
                    TextBox2.Text = "";
                    TextBox3.Text = "";
                    txtaddress.Text = "";
                    txtqulfction.Text = "";
                    TextBox1.Text = "";
                    autogenerated();
                    GridView1.DataBind();
                }
                else
                {
                    cmd = new SqlCommand("insert into AddEmployee(EmployeeId,EmployeeName,Email,Mobile,Qualification,Aaddress,Gender,Designation,city,BasicSalary,EmergencyNo,AlternateNo) values('" + txt1.Text + "','" + txt2.Text + "','" + txt3.Text + "','" + txt4.Text + "','" + txtqulfction.Text + "','" + txtaddress.Text.Replace("'", "''") + "','" + radio1.SelectedValue.ToString() + "','" + txtdsgntion.Text + "','" + txtcity.Text + "','" + TextBox1.Text + "','"+TextBox2.Text+"','"+TextBox3.Text+"')", conn);
                    conn.Open();
                    SqlDataReader dr = cmd.ExecuteReader();
                    conn.Close();
                    txtdsgntion.Text = "";
                    txtcity.Text = "";
                    txt2.Text = "";
                    txt3.Text = "";
                    TextBox1.Text = "";
                    txt4.Text = "";
                    txtaddress.Text = "";
                    txtqulfction.Text = "";
                    TextBox2.Text = "";
                    TextBox3.Text = "";
                    autogenerated();
                    GridView1.DataBind();
                }
               
            }
            catch (Exception)
            {

                Response.Write("<script language='javascript'>alert('Dont use special characters in filling blanks')</script>");
            }
            finally
            {

            }
        }
        private void autogenerated()
        {
            string code = "SIPL";
            conn.Open();
            SqlCommand cmd = new SqlCommand("Select max(id) from AddEmployee", conn);
            int i = Convert.ToInt32(cmd.ExecuteScalar());
            conn.Close();
            i++;
            txt1.Text = code + i.ToString();
        }
    }
}