using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Data;
using System.Configuration;
using System.IO;
namespace SwankInnovation
{
    public partial class AddVender : System.Web.UI.Page
    {
        SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["Swank"].ConnectionString);
        SqlCommand cmd;
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                autogenerated();
                GridView1.DataBind();
            }
        }
        protected void btnSubmit_Click(object sender, EventArgs e)
        {
            string folderPath = Server.MapPath("~/Swank/");
            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }
            if (fileupload1.HasFile && fileupload2.HasFile)
            {
                fileupload1.SaveAs(folderPath + Path.GetFileName(fileupload1.FileName));
                //Image1.ImageUrl = "~/Swank/" + Path.GetFileName(fileupload1.FileName);
                fileupload2.SaveAs(folderPath + Path.GetFileName(fileupload2.FileName));
                //Image2.ImageUrl = "~/Swank/" + Path.GetFileName(fileupload2.FileName);

                cmd = new SqlCommand("insert into AddVendor(VendorID,VendorName,Mobile,Email,Address,City,Gender,Aadharcard,Pancard,PancardNo) values('" + TextBox1.Text + "','" + txt2.Text + "','" + txt3.Text + "','" + txt4.Text + "','" + txt5.Text.Replace("'", "''") + "','" + txt6.Text + "','" + radio1.SelectedValue + "','" + "~/Swank/" + fileupload1.FileName + "','" + "~/Swank/" + fileupload2.FileName + "','"+TextBox2.Text+"')", conn);
                conn.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                conn.Close();
                txt2.Text = "";
                txt3.Text = "";
                txt4.Text = "";
                txt5.Text = "";
                txt6.Text = "";
                TextBox2.Text = "";
                autogenerated();
                GridView1.DataBind();
            }
            else
            {
                cmd = new SqlCommand("insert into AddVendor(VendorID,VendorName,Mobile,Email,Address,City,Gender,PancardNo) values('" + TextBox1.Text + "','" + txt2.Text + "','" + txt3.Text + "','" + txt4.Text + "','" + txt5.Text.Replace("'", "''") + "','" + txt6.Text + "','" + radio1.SelectedValue + "','"+TextBox2.Text+"')", conn);
                conn.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                conn.Close();
                txt2.Text = "";
                txt3.Text = "";
                txt4.Text = "";
                txt5.Text = "";
                txt6.Text = "";
                TextBox2.Text = "";
                autogenerated();
                GridView1.DataBind();
            }
        }
        private void autogenerated()
        {
            string code = "SIPL";
            conn.Open();
            SqlCommand cmd = new SqlCommand("Select max(id) from AddVendor", conn);
            int i = Convert.ToInt32(cmd.ExecuteScalar());
            conn.Close();
            i++;
            TextBox1.Text = code + i.ToString();
        }
    }
}