using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Data;
using System.Configuration;
namespace SwankInnovation
{
    public partial class Holiday : System.Web.UI.Page
    {
        SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["Swank"].ConnectionString);
        protected void Page_Load(object sender, EventArgs e)
        {
            txtDate.Text = DateTime.Now.ToShortDateString();
            if (!IsPostBack)
            {
                autogenerated();
                reset();
            }
        }
        private void reset()
        {
            dd2.ClearSelection();
            txtFdate.Text = string.Empty;
            txtTdate.Text = string.Empty;
        }
        private void autogenerated()
        {
            string code = "HolidayId-";
            conn.Open();
            SqlCommand cmd = new SqlCommand("Select max(Id) from Holidays", conn);
            int i = Convert.ToInt32(cmd.ExecuteScalar());
            conn.Close();
            i++;
            txtId.Text = code + i.ToString();
        }
        protected void btnSubmit_Click(object sender, EventArgs e)
        {
            SqlCommand Comm = new SqlCommand("insert into Holidays values('" + txtId.Text + "','"+txtDate.Text+"','" + dd2.Text.Replace("'", "''") + "','" + txtFdate.Text + "','" + txtTdate.Text + "')", conn);
            conn.Open();
            Comm.ExecuteNonQuery();
            conn.Close();
            reset();
            autogenerated();
            GridView1.DataBind();
            dd2.SelectedValue = "0";
        }
    }
}